model:
    type: "EfficientB2MulFeatureWeightNetMall"
    pretrained: True
dataset:
    train:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 100
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IPOID_database/all_images/"
        IQA_transforms:
           - type: "default_loader2"
             IQA_type: "NR"
           - type: "Resize"
             IQA_type: "NR"
             img_size: [960,540]
           - type: "RandomVerticleFlip"
           - type: "RandomHorizontalFlip"
           - type: "ToTensor"
             IQA_type: "NR"
    val:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 100
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IPOID_database/all_images/"
        IQA_transforms:
           - type: "default_loader2"
             IQA_type: "NR"
           - type: "Resize"
             IQA_type: "NR"
             img_size: [960,540]
           - type: "ToTensor"
             IQA_type: "NR"

train_config:
   train_batch_size: 8
   val_batch_size: 1
   epoch: 120
   save_epoch: 60
   val_epoch: 1
   log_iter: 50
   checkpoint_dir: "path"

optimizer:
   type: "Adam"
   lr: 0.0001

lr_scheduler:
   type: "StepLR"
   step_size: 60
   gamma: 0.1
loss:
   type: "L1Loss"
   reduction: 'mean'
gpu_ids: [8]