model:
    type: "EfficientB2MulFeatureWeightNetMall"
    pretrained: False
dataset:
    train:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 1
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IQAtrain/crop_database/CSIQ/crop128_stride64"
        IQA_transforms:
           - type: "default_loader2"
             IQA_type: "NR"
           - type: "RandomVerticleFlip"
           - type: "RandomHorizontalFlip"
           - type: "RandomRotate90"
           - type: "ToTensor"
             IQA_type: "NR"
    val:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 1
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IQAtrain/ori_database/CSIQ/dst_imgs/"
        IQA_transforms:
           - type: "default_loader2"
             IQA_type: "NR"
           - type: "ToTensor"
             IQA_type: "NR"

train_config:
   train_batch_size: 128
   val_batch_size: 1
   epoch: 80
   save_epoch: 30
   val_epoch: 1
   log_iter: 100
   checkpoint_dir: "path"

optimizer:
   type: "Adam"
   lr: 0.01

lr_scheduler:
   type: "StepLR"
   step_size: 5
   gamma: 0.75

loss:
   type: "L1Loss"
   reduction: 'mean'
gpu_ids: [0,7]