model:
    type: "EfficientB2MulFeatureWeightNet"
    pretrained: True
dataset:
    train:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 100
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IQAtrain/crop_database/LIVE/crop128_stride64"
        IQA_transforms:
           - type: "default_loader3"
             IQA_type: "NR"
           - type: "RandomVerticleFlip"
           - type: "RandomHorizontalFlip"
           - type: "RandomRotate90"
           - type: "ToTensor"
             IQA_type: "NR"
    val:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 100
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IQAtrain/ori_database/LIVE/databaserelease2/"
        IQA_transforms:
           - type: "default_loader3"
             IQA_type: "NR"
           - type: "ToTensor"
             IQA_type: "NR"

train_config:
   train_batch_size: 256
   val_batch_size: 1
   epoch: 50
   save_epoch: 30
   val_epoch: 1
   log_iter: 100
   checkpoint_dir: "path"

optimizer:
   type: "Adam"
   lr: 0.0001

lr_scheduler:
   type: "StepLR"
   step_size: 20
   gamma: 0.5

loss:
   type: "L1Loss"
   reduction: 'mean'
gpu_ids: [6]