model:
    type: "EfficientB2MulFeatureWeightNet"
    pretrained: True
dataset:
    train:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 1
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IQAtrain/crop_database/CSIQ/crop224_stride112"
        IQA_transforms:
           - type: "default_loader2"
             IQA_type: "NR"
           - type: "ToTensor"
             IQA_type: "NR"
           - type: "Normalize"
             mean: [0.485, 0.456, 0.406]
             std: [0.229, 0.224, 0.225]
    val:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 1
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IQAtrain/ori_database/CSIQ/dst_imgs/"
        IQA_transforms:
           - type: "default_loader2"
             IQA_type: "NR"
           - type: "ToTensor"
             IQA_type: "NR"
           - type: "Normalize"
             mean: [0.485, 0.456, 0.406]
             std: [0.229, 0.224, 0.225]

train_config:
   train_batch_size: 64
   val_batch_size: 1
   epoch: 30
   save_epoch: 15
   val_epoch: 1
   log_iter: 100
   checkpoint_dir: "path"

optimizer:
   type: "Adam"
   lr: 0.001

loss:
   type: "L1Loss"
   reduction: 'mean'
gpu_ids: [8]