model:
    type: "EfficientB2MulFeatureWeightNet"
    pretrained: False
dataset:
    train:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 100
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IPOIDtraining/crop224_stride112"
        IQA_transforms:
           - type: "default_loader2"
             IQA_type: "NR"
           - type: "RandomVerticleFlip"
           - type: "RandomHorizontalFlip"
           - type: "RandomRotate90"
           - type: "ToTensor"
             IQA_type: "NR"
    val:
        type: "CustomDatabase"
        IQA_type: "NR"
        nor_value: 100
        img_info_file: "xxx.txt"
        dis_img_path: "/home/hxm/IPOID_IQA/IPOID_database/all_images/"
        IQA_transforms:
           - type: "default_loader2"
             IQA_type: "NR"
           - type: "ToTensor"
             IQA_type: "NR"

train_config:
   train_batch_size: 128
   val_batch_size: 1
   epoch: 25
   save_epoch: 20
   val_epoch: 1
   log_iter: 1000
   checkpoint_dir: "path"

optimizer:
   type: "Adam"
   lr: 0.01

lr_scheduler:
   type: "StepLR"
   step_size: 1
   gamma: 0.75

loss:
   type: "L1Loss"
   reduction: 'mean'
gpu_ids: [6]